modLoader="javafml"
loaderVersion="[3,)"
license="LGPL-3.0-or-later"
showAsResourcePack=false

[[mods]]
modId="caustica"
version="${version}"
displayName="Caustica"
authors="i"
description='''Hardware-ray-traced renderer with DLSS Ray Reconstruction for the Minecraft Vulkan backend.'''
displayTest="IGNORE_ALL_VERSION"

[[mixins]]
config="caustica.mixins.json"

[[mixins]]
config="caustica.neoforge.mixins.json"

[[dependencies.caustica]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.caustica]]
modId="minecraft"
type="required"
versionRange="[26.2,26.3)"
ordering="NONE"
side="CLIENT"
